"""Renders markdown research briefs into styled PDF documents using WeasyPrint in a thread worker."""

import asyncio
import logging
import os
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional
import markdown
from app.core.config import settings

logger = logging.getLogger("techradar.pdf_generator")

# Base styling for WeasyPrint
ENTERPRISE_PDF_CSS = """
@page {
    size: A4;
    margin: 20mm 15mm 20mm 15mm;
    @top-left {
        content: "AUTONOMOUS TECH RADAR • EXECUTIVE BRIEFING";
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
        font-size: 7.5pt;
        font-weight: 700;
        color: #718096;
        letter-spacing: 0.8px;
    }
    @top-right {
        content: "CONFIDENTIAL & PROPRIETARY";
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
        font-size: 7.5pt;
        font-weight: 600;
        color: #e53e3e;
        letter-spacing: 0.8px;
    }
    @bottom-left {
        content: "Generated by LangGraph Autonomous JIT Learning Agent";
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
        font-size: 7.5pt;
        color: #a0aec0;
    }
    @bottom-right {
        content: "Page " counter(page) " of " counter(pages);
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
        font-size: 7.5pt;
        font-weight: 600;
        color: #4a5568;
    }
}

body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
    font-size: 10pt;
    line-height: 1.6;
    color: #1a202c;
    background-color: #ffffff;
    margin: 0;
    padding: 0;
}

.document-header {
    border-bottom: 2px solid #2b6cb0;
    padding-bottom: 12px;
    margin-bottom: 24px;
}

.radar-badge {
    display: inline-block;
    background-color: #ebf8ff;
    color: #2b6cb0;
    font-size: 8pt;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 1px;
    padding: 4px 10px;
    border-radius: 4px;
    margin-bottom: 8px;
    border: 1px solid #bee3f8;
}

h1 {
    font-size: 22pt;
    line-height: 1.25;
    color: #1a365d;
    margin: 4px 0 10px 0;
    font-weight: 800;
}

.meta-bar {
    font-size: 8.5pt;
    color: #718096;
    margin-bottom: 8px;
}

h2 {
    font-size: 14pt;
    color: #2b6cb0;
    border-bottom: 1px solid #e2e8f0;
    padding-bottom: 4px;
    margin-top: 22px;
    margin-bottom: 10px;
    font-weight: 700;
    page-break-after: avoid;
}

h3 {
    font-size: 11pt;
    color: #2d3748;
    margin-top: 16px;
    margin-bottom: 6px;
    font-weight: 600;
    page-break-after: avoid;
}

p {
    margin: 0 0 10px 0;
    text-align: justify;
}

/* Callout Box Containers */
.callout-hype {
    background-color: #fff5f5;
    border-left: 4px solid #e53e3e;
    padding: 10px 14px;
    margin: 14px 0;
    border-radius: 0 4px 4px 0;
}

.callout-reality {
    background-color: #f0fff4;
    border-left: 4px solid #38a169;
    padding: 10px 14px;
    margin: 14px 0;
    border-radius: 0 4px 4px 0;
}

.callout-architecture {
    background-color: #ebf8ff;
    border-left: 4px solid #3182ce;
    padding: 10px 14px;
    margin: 14px 0;
    border-radius: 0 4px 4px 0;
}

.callout-warning {
    background-color: #fffaf0;
    border-left: 4px solid #dd6b20;
    padding: 10px 14px;
    margin: 14px 0;
    border-radius: 0 4px 4px 0;
}

.callout-title {
    font-weight: 700;
    font-size: 9pt;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    margin-bottom: 4px;
}

.callout-hype .callout-title { color: #c53030; }
.callout-reality .callout-title { color: #276749; }
.callout-architecture .callout-title { color: #2b6cb0; }
.callout-warning .callout-title { color: #c05621; }

/* Code Containers with Dark Mode Syntax Highlighting */
pre {
    background-color: #1e1e2e;
    color: #cdd6f4;
    font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, Courier, monospace;
    font-size: 8.5pt;
    line-height: 1.45;
    padding: 12px 14px;
    border-radius: 6px;
    overflow-x: auto;
    border: 1px solid #313244;
    margin: 12px 0;
    page-break-inside: avoid;
}

code {
    font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, Courier, monospace;
    font-size: 8.5pt;
    background-color: #edf2f7;
    color: #c53030;
    padding: 2px 5px;
    border-radius: 3px;
}

pre code {
    background-color: transparent;
    color: inherit;
    padding: 0;
}

table {
    width: 100%;
    border-collapse: collapse;
    margin: 14px 0;
    font-size: 9pt;
}

th, td {
    border: 1px solid #e2e8f0;
    padding: 6px 10px;
    text-align: left;
}

th {
    background-color: #f7fafc;
    font-weight: 600;
    color: #4a5568;
}

ul, ol {
    margin: 0 0 10px 0;
    padding-left: 20px;
}

li {
    margin-bottom: 4px;
}
"""


class PDFGeneratorService:
    """Converts markdown text into styled PDF files."""

    def __init__(self, output_dir: Optional[str] = None):
        self.output_dir = Path(output_dir or settings.PDF_OUTPUT_DIR)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def _transform_callouts(self, html: str) -> str:
        """Replace custom blockquote tags with styled callout cards."""
        # Transform [!HYPE], [!REALITY], [!ARCHITECTURE], [!WARNING]
        patterns = [
            (r"<blockquote>\s*<p>\s*\[!HYPE\]\s*(.*?)</p>\s*</blockquote>",
             r'<div class="callout-hype"><div class="callout-title">🚨 Hype Analysis</div><p>\1</p></div>'),
            (r"<blockquote>\s*<p>\s*\[!REALITY\]\s*(.*?)</p>\s*</blockquote>",
             r'<div class="callout-reality"><div class="callout-title">✅ Production Reality</div><p>\1</p></div>'),
            (r"<blockquote>\s*<p>\s*\[!ARCHITECTURE\]\s*(.*?)</p>\s*</blockquote>",
             r'<div class="callout-architecture"><div class="callout-title">🏛️ Architectural Blueprint</div><p>\1</p></div>'),
            (r"<blockquote>\s*<p>\s*\[!WARNING\]\s*(.*?)</p>\s*</blockquote>",
             r'<div class="callout-warning"><div class="callout-title">⚠️ Engineering Warning</div><p>\1</p></div>'),
        ]

        transformed = html
        for pat, repl in patterns:
            transformed = re.sub(pat, repl, transformed, flags=re.DOTALL | re.IGNORECASE)
        return transformed

    def compile_html(self, markdown_text: str, title: str) -> str:
        """Convert markdown text into a full styled HTML document."""
        md_extensions = ["extra", "codehilite", "tables", "admonition", "fenced_code"]
        raw_body_html = markdown.markdown(markdown_text, extensions=md_extensions)
        styled_body = self._transform_callouts(raw_body_html)

        current_date = datetime.now(timezone.utc).strftime("%B %d, %Y • %H:%M UTC")

        full_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{title}</title>
    <style>
        {ENTERPRISE_PDF_CSS}
    </style>
</head>
<body>
    <div class="document-header">
        <div class="radar-badge">Enterprise Autonomous Tech Radar</div>
        <h1>{title}</h1>
        <div class="meta-bar">
            <strong>Published:</strong> {current_date} &nbsp;|&nbsp; 
            <strong>Classification:</strong> Tier-1 Engineering &nbsp;|&nbsp; 
            <strong>Engine:</strong> LangGraph JIT Learning Node
        </div>
    </div>
    <div class="content-container">
        {styled_body}
    </div>
</body>
</html>"""
        return full_html

    def _sync_render_pdf(self, html_content: str, destination_path: Path) -> None:
        """Render HTML to PDF synchronously using WeasyPrint (or write HTML fallback)."""
        try:
            import weasyprint
            weasyprint.HTML(string=html_content).write_pdf(target=str(destination_path))
            logger.info(f"WeasyPrint successfully compiled PDF at: {destination_path}")
        except ImportError:
            logger.warning("WeasyPrint library not available. Writing raw HTML fallback artifact.")
            fallback_html_path = destination_path.with_suffix(".html")
            fallback_html_path.write_text(html_content, encoding="utf-8")
            # Write a minimal valid PDF placeholder if weasyprint cannot be imported
            destination_path.write_bytes(
                b"%PDF-1.4\n1 0 obj<< /Title (" + destination_path.stem.encode("utf-8") + b") >>\ntrailer<< /Root 1 0 R >>\n%%EOF"
            )
        except Exception as e:
            logger.error(f"Error during WeasyPrint rendering: {e}", exc_info=True)
            fallback_html_path = destination_path.with_suffix(".html")
            fallback_html_path.write_text(html_content, encoding="utf-8")
            destination_path.write_bytes(b"%PDF-1.4\n%%EOF\n")

    async def generate_pdf(self, markdown_text: str, title: str, filename_prefix: str = "tutorial") -> str:
        """Compile markdown to PDF off-thread and return the file path."""
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        safe_prefix = "".join(c for c in filename_prefix if c.isalnum() or c in ("-", "_")).lower()
        filename = f"{safe_prefix}_{timestamp}.pdf"
        output_path = self.output_dir / filename

        html_content = self.compile_html(markdown_text, title)

        # Offload to thread to keep the event loop responsive
        await asyncio.to_thread(self._sync_render_pdf, html_content, output_path)

        return str(output_path.resolve())
