"""
Pydantic v2 schemas and Data Transfer Objects (DTOs).
Enforces strict type safety and input validation across REST API endpoints,
LangGraph agent state payloads, and notification delivery mechanisms.
"""

from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field, HttpUrl, field_validator


class TechReleaseItem(BaseModel):
    """Represents an ingested technical publication, paper, or release."""
    model_config = ConfigDict(extra="ignore")

    title: str = Field(..., min_length=3, max_length=500, description="Headline or paper title")
    source_url: str = Field(..., description="Canonical source URL")
    summary: str = Field(..., min_length=10, description="Extracted synopsis or abstract")
    source_type: str = Field(..., description="Origin identifier: hackernews, arxiv, github, webhook")
    published_at: Optional[datetime] = Field(default=None, description="Publication timestamp")
    content_hash: Optional[str] = Field(default=None, description="SHA-256 idempotency fingerprint")
    raw_payload: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Raw source JSON payload")


class UserProfileCreate(BaseModel):
    """Payload schema for registering or onboarding a new developer profile."""
    model_config = ConfigDict(extra="forbid")

    user_id: str = Field(..., min_length=3, max_length=64, description="Unique developer username or ID")
    discord_id: Optional[str] = Field(default=None, max_length=64, description="Discord Snowflake ID")
    telegram_chat_id: Optional[str] = Field(default=None, max_length=64, description="Telegram Chat ID or Username")
    tracked_domains: List[str] = Field(default_factory=list, description="List of technical domains")
    ignored_keywords: List[str] = Field(default_factory=list, description="Negative filter keyword list")
    profile_summary: Optional[str] = Field(default="", description="High-level developer stack description")
    similarity_threshold: Optional[float] = Field(default=0.82, ge=0.0, le=1.0)


class UserProfileUpdate(BaseModel):
    """Payload schema for updating existing developer radar criteria."""
    model_config = ConfigDict(extra="forbid")

    tracked_domains: Optional[List[str]] = Field(default=None)
    ignored_keywords: Optional[List[str]] = Field(default=None)
    similarity_threshold: Optional[float] = Field(default=None, ge=0.0, le=1.0)
    profile_summary: Optional[str] = Field(default=None)
    discord_id: Optional[str] = Field(default=None)
    telegram_chat_id: Optional[str] = Field(default=None)


class UserProfileResponse(BaseModel):
    """Serialized representation of a persisted developer profile."""
    model_config = ConfigDict(from_attributes=True)

    user_id: str
    discord_id: Optional[str]
    telegram_chat_id: Optional[str]
    tracked_domains: List[str]
    ignored_keywords: List[str]
    profile_summary: str
    similarity_threshold: float
    created_at: datetime
    updated_at: datetime


class SearchPlan(BaseModel):
    """Execution strategy generated by the Planner Node for multi-source ingestion."""
    model_config = ConfigDict(extra="ignore")

    user_id: str = Field(default="default_user")
    discovery_mode: str = Field(default="latest", description="'latest' or 'foundational'")
    arxiv_categories: List[str] = Field(default_factory=list, description="Target arXiv categories e.g. cs.CV, cs.CR, math.QA")
    arxiv_query_terms: List[str] = Field(default_factory=list, description="Specific terms for title/abstract search")
    arxiv_sort_by: str = Field(default="submittedDate", description="'submittedDate' or 'relevance'")
    arxiv_sort_order: str = Field(default="descending")
    github_topics: List[str] = Field(default_factory=list, description="GitHub topic filters")
    github_search_query: str = Field(default="language:python stars:>100")
    anchor_concepts: List[str] = Field(default_factory=list, description="Key technical terms for grounding & validation")
    verification_anchor_concepts: List[str] = Field(default_factory=list, description="Verification grounding terms")
    negative_filters: List[str] = Field(default_factory=list)


class AlertPayload(BaseModel):
    """Standardized payload dispatched to communication adapters (Discord, Telegram)."""
    thread_id: str = Field(..., description="Unique LangGraph workflow checkpoint execution ID")
    release_title: str
    release_summary: str
    source_url: str
    matched_domains: List[str] = Field(default_factory=list)
    relevance_score: float
    recipient_id: str
    channel: str = Field(default="DISCORD", description="Target notification medium: DISCORD or TELEGRAM")
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict)


class InteractionCallback(BaseModel):
    """Webhook action payload triggered by user response on Discord or Telegram."""
    custom_id: str = Field(..., description="Callback action identifier, e.g. action:generate:<thread_id>")
    thread_id: str
    action: str = Field(..., description="Action decision: generate_tutorial or skip_release")
    user_id: str
    override_prompt: Optional[str] = Field(default=None, description="Custom prompt instructions provided by user")


class TelegramFromUser(BaseModel):
    """Telegram User payload schema."""
    model_config = ConfigDict(extra="ignore")
    id: int
    is_bot: Optional[bool] = False
    first_name: Optional[str] = ""
    username: Optional[str] = None


class TelegramChat(BaseModel):
    """Telegram Chat payload schema."""
    model_config = ConfigDict(extra="ignore")
    id: int
    type: Optional[str] = "private"
    title: Optional[str] = None
    username: Optional[str] = None


class TelegramMessage(BaseModel):
    """Telegram Message payload schema."""
    model_config = ConfigDict(extra="ignore")
    message_id: int
    from_user: Optional[TelegramFromUser] = Field(default=None, alias="from")
    chat: TelegramChat
    text: Optional[str] = None


class TelegramCallbackQuery(BaseModel):
    """Telegram Inline Keyboard Callback Query schema."""
    model_config = ConfigDict(extra="ignore")
    id: str
    from_user: TelegramFromUser = Field(alias="from")
    message: Optional[TelegramMessage] = None
    data: Optional[str] = None


class TelegramUpdate(BaseModel):
    """Standard incoming Telegram Bot API webhook Update schema."""
    model_config = ConfigDict(extra="ignore")
    update_id: int
    message: Optional[TelegramMessage] = None
    callback_query: Optional[TelegramCallbackQuery] = None


class ResearchOutput(BaseModel):
    """Structured research notes gathered from external technical scrapers."""
    query: str
    sources: List[Dict[str, Any]] = Field(default_factory=list)
    synthesized_findings: str


class TutorialDraft(BaseModel):
    """Structured technical tutorial ready for compilation into publication-grade PDF."""
    title: str
    executive_summary: str
    architecture_breakdown: str
    hype_vs_reality: str
    code_samples: str
    markdown_content: str
